name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Run lint
      run: npm run lint 
    - name: Run prettier
      run: npm run prettier
