name: Github Actions Example

on:
  pull_request:
  push:

jobs:
  test:
    name: Running linter and prettier
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: lint
      run: npm run lint
    - name: prettier
      run: npm run prettier
