name: GitHub Actions Demo
on: [push]
jobs:
  check:
    name: Running EsLint and prettier
#   Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run lint
      run: npm run lint 
    - name: Run prettier
      run: npm run prettier
